### ISSUE TITLE
Why I see "No associated EVS disks available."?

### ISSUE THREAD

**Issue by gabbler97** [opentelekomcloud-docs/cloud-backup-recovery#97]
Hello All,
I have this issue right now. Maybe I am missing something.
I have a volume created by a CSI provisioner in my CCE cluster.

![Image](https://github.com/user-attachments/assets/f2340f14-6617-4b1f-89e9-efaab851cd65)

I have crated a vault for that so I can have automated daily backups with a policy.

![Image](https://github.com/user-attachments/assets/4abdd442-9ee3-4b9c-99f7-d84f8cfd0994)

![Image](https://github.com/user-attachments/assets/8e69b419-187f-4e4a-b639-5e036521bb5c)

![Image](https://github.com/user-attachments/assets/63a9d4c6-d690-4d18-b066-cc0582a4fedf)

I have created the PVC with the basic csi-disk storageclass.

```YAML
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-disk
parameters:
  csi.storage.k8s.io/csi-driver-name: disk.csi.everest.io
  csi.storage.k8s.io/fstype: ext4
  everest.io/disk-volume-type: SAS
  everest.io/passthrough: "true"
provisioner: everest-csi-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Any help on this topic is appreciated!
Thank you in advance!
